### ISSUE TITLE
Error deploying yaml in AWS

### ISSUE THREAD

**Issue by csarora** [madeden/blogposts#1]
I am getting below error on AWS

~/blogposts/k8s-federation# uname -a
Linux ip-172-31-26-62 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

~/blogposts/k8s-federation# juju deploy src/bundle/k8s-aws.yaml
**ERROR charm or bundle URL has invalid form: "src/bundle/k8s-aws.yaml"**

**Comment by SaMnCo** [comment]
Sorry, I didn't get a notification of this error just saw it randomly checking the repo. I'll look into it and come back to you asap.

**Comment by SaMnCo** [comment]
OK I kept some unnecessary constraints in there. You can safely start again.
